// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// getMAInt
Rcpp::List getMAInt(Eigen::Map<Eigen::MatrixXi>& X);
RcppExport SEXP popkin_getMAInt(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXi>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(getMAInt(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"popkin_getMAInt", (DL_FUNC) &popkin_getMAInt, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_popkin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
